
train_file: ['data/ADNI_train.json']
val_file: ['data/ADNI_val.json']
test_file: ['data/ADNI_test.json']

# Patch settings
patch_size: 32
# Note: This resolution is different from Pretrain. 
# The code handles this via interpolation now.
image_res: [128, 96, 128] 
in_chans: 1

# Model Architecture
vision_width: 768
embed_dim: 256
depth: 6
num_heads: 12

# Training Hyperparameters for SMALL DATA (7 Subjects)
# Batch size must be smaller than 7
batch_size: 2
# Queue size MUST match the Pretrain checkpoint (64)
queue_size: 64 

# Standard params
temp: 0.07
mlm_probability: 0.25
momentum: 0.995
alpha: 0.4

# Optimizer & Scheduler
optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 50, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 5, cooldown_epochs: 0}